services:
  external-server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python3", "/home/bringauto/external_server/external_server_main.py", "-c", "./config/for_docker.json"]
    restart: always
    volumes:
      - "./config:/home/bringauto/config"
      - "./log:/home/bringauto/log"
    networks:
      - bring-emulator

networks:
  bring-emulator:
    name: bring-emulator
