services:
  external-server:
    image: external-server
    entrypoint: ["python3", "/home/bringauto/external_server/external_server_main.py", "-c", "/home/bringauto/config/for_docker.json"]
    restart: always
    networks:
      - bring-emulator

networks:
  bring-emulator:
    name: bring-emulator
