services:
  external-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./config/for_docker.json"
    restart: always
    volumes:
      - "./config:/home/bringauto/config/"
      - "./log:/home/bringauto/log/"
    networks:
      - bring-emulator
    depends_on:
      initialize-log-folders:
        condition: service_started

  initialize-log-folders:
    image: ubuntu:24.04
    restart: "no"
    volumes:
      - ./log:/home/bringauto/log/
    entrypoint:
      ["/usr/bin/chown", "-R", "5000:5000", "/home/bringauto/log"]

networks:
  bring-emulator:
    name: bring-emulator

